/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.65
 * Generated at: 2022-12-19 18:35:49 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.com.yju._2wda.ryu.view.boardgame;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.io.PrintWriter;

public final class boardgame_005fc_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {


	
	static final String rootDir = "/rwk51_boardgame_mall"; //DBCP 경로 다이렉토리로 지정
	static final String workDir = rootDir +"/com/yju/2wda/ryu"; //우리가 파일을 저장해준 경로를 지정한다.
	
	static final String modelDir = workDir +"/model"; //workDir안에 있는 model 경로에 접속
	static final String viewDir = workDir + "/view"; //workDir안에 있는 view 경로에 접속
	static final String contDir = workDir +"/controller"; //workDir안에 있는 controller에 접속
	
	static final String userModelDir = modelDir + "/user"; //modelDir경로의 beer에 접속
	static final String userViewDir = viewDir + "/user"; //view경로의 user 에 접속
	
	static final String boardgameModelDir = modelDir + "/boardgame"; //boardgameview model 경로설정
	static final String boardgameViewDir = viewDir +"/boardgame"; //boardgameview 경로 설정
	
	static final String etcViewDir = viewDir + "/etc"; //viewDir에 기타에 접속
	
	static final String imgDir = rootDir + "/image"; //이미지경로
	static final String oriDir = imgDir + "/original"; //원본이미지
	static final String thuDir = imgDir + "/thumb"; //썸네일이미지
	
	static final String CSSDir = rootDir +"/CSS"; //CSS 경로
	
	static final String jsDir = rootDir +"/JS"; //자바스크립트 경로
	static final String jsUserDir = jsDir +"/user"; //자바스크립트 안의 user 폴더의 경로
	static final String jsBoardgameDir = jsDir +"/boardgame"; //boardgmae 폴더의 경로
	


  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/footer.jsp", Long.valueOf(1669251909750L));
    _jspx_dependants.put("/globalData.jsp", Long.valueOf(1670463560061L));
    _jspx_dependants.put("/header.jsp", Long.valueOf(1671463002273L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.io.PrintWriter");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write('\r');
      out.write('\n');
      out.write(' ');
      out.write("\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width\", initial-scale=\"1\">\r\n");
      out.write("\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");

	if( session.isNew()){ //새로운 객체가 만들어졌다면 세션을 저장한다. 
		session.setAttribute("loginState", "logout"); //로그인 상태저장
		session.setAttribute("viewState", null); //지금 보는 화면 저장
		session.setAttribute("user_num", null); //유저 번호 저장
		session.setAttribute("user_name", null); //유저 이름 저장
		session.setAttribute("user_id", null); //유저 아이디 저장
		session.setAttribute("user_passwd", null); //유저 비번 저장
		session.setAttribute("user_class", null); //유저 등급 저장	
	}

      out.write("\r\n");
      out.write("<nav class=\"navbar navbar-light\" id=\"navigationBox\">\r\n");
      out.write("	<a class=\"navbar-brand\"  href=\"");
      out.print(rootDir );
      out.write("/index.jsp\">\r\n");
      out.write("		<img src=\"");
      out.print(imgDir);
      out.write("/logo.png\" style=\"max-width: 100%; height: 0%;\"/>\r\n");
      out.write("	</a>\r\n");
      out.write("\r\n");
      out.write("	\r\n");
      out.write("	<div align = \"center\">\r\n");
      out.write("		\r\n");
      out.write("		<form id=\"form\" method=\"post\" action=\"./searchBoardgame.be\" >\r\n");
      out.write("		\r\n");
      out.write("		<select name = \"b_category\" id = \"b_category\">\r\n");
      out.write("				<option value = \"all\" selected>전체</option>\r\n");
      out.write("				<option value = \"strategy\" >전략</option>\r\n");
      out.write("				<option value = \"party\">파티</option>\r\n");
      out.write("				<option value = \"new\">신상</option>\r\n");
      out.write("				<option value = \"school\">교구</option>\r\n");
      out.write("				<option value = \"first\">선 주문</option>\r\n");
      out.write("				<option value = \"best\">베스트</option>\r\n");
      out.write("			</select>\r\n");
      out.write("			<input type=\"text\" name =\"search\">\r\n");
      out.write("			<input type =\"hidden\" name = \"currentPageNo\" value = 0>\r\n");
      out.write("			<input type=\"submit\" value=\"상품검색\">\r\n");
      out.write("			\r\n");
      out.write("			\r\n");
      out.write("		</form>\r\n");
      out.write("		\r\n");
      out.write("	</div>\r\n");
      out.write("	 ");

		if(session.getAttribute("loginState").equals("login") ){ // loginState의 상태가 로그인이라면 

      out.write("\r\n");
      out.write("	\r\n");
      out.write("		<!-- 유저아이디 띄우고 로그인 상태 알려주기  밑에 로직은 로그아웃 버튼을 추가하고 기능   -->\r\n");
      out.write("		<div id=\"loginForm\">\r\n");
      out.write("			<!-- <nav class=\"navbar navbar-default\"> -->\r\n");
      out.write("				<table>\r\n");
      out.write("				<tr>				\r\n");
      out.write("					<td><b>");
      out.print(session.getAttribute("user_id"));
      out.write("</b>님 반가워요!</td>\r\n");
      out.write("					<br>\r\n");
      out.write("					<td>&nbsp&nbsp</td>\r\n");
      out.write("					<form method=\"post\" action=\"./logoutUser.be\">\r\n");
      out.write("						<td style=\"text-align: center;\">\r\n");
      out.write("							<button type=\"submit\" name=\"actionType\" value=\"LOGOUT\" class=\"btn btn-primary\" >로그아웃</button>\r\n");
      out.write("						</td>\r\n");
      out.write("					</form>\r\n");
      out.write("					\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td>\r\n");
      out.write("						<a href=\"./getMyInfo.be\">마이페이지</a>\r\n");
      out.write("					</td>\r\n");
      out.write("				</tr>\r\n");
      out.write("			</table>\r\n");
      out.write("\r\n");
      out.write("		</div>\r\n");
      out.write("		\r\n");

		}
		else
		{ //로그인 상태가 아니라면

      out.write("	 \r\n");
      out.write("		<!-- 아이디,비밀번호를 입력하는 창을 띄워주고 로그인을 시도한다면 정보를 전달한다. -->\r\n");
      out.write("		 ");
			
			if(session.getAttribute("loginState").equals("errorID") || session.getAttribute("loginState").equals("errorPW") ){
				PrintWriter script = response.getWriter();
				script.println("<script>");
				script.println("alert('아이디 혹은 비밀번호가 잘못되었습니다.')");
				script.println("</script>");
				session.setAttribute("loginState", "logout");
			}
		

      out.write(" 	\r\n");
      out.write("	<div id=\"loginForm\">\r\n");
      out.write("	 <form method=\"post\" action=\"./loginUser.be\">\r\n");
      out.write("	 	<table style=\"border-collapse: separate; border-spacing: 30px 0;\">\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td><input type=\"text\" placeholder=\"아이디\" class=\"form-control form-control-sm\" id=\"idForm\" name=\"user_id\" ></td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td><input type=\"password\" placeholder=\"비밀번호\" class=\"form-control form-control-sm\" id=\"pwForm\" name=\"user_passwd\"></td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td colspan=\"3\" style=\"text-align: center;\">\r\n");
      out.write("					<button type=\"submit\" name=\"actionType\" value=\"LOGIN\" class=\"btn btn-primary\">로그인</button>\r\n");
      out.write("							\r\n");
      out.write("					<button type=\"submit\" formaction=\"");
      out.print(userViewDir );
      out.write("/user_c.jsp\"  class=\"btn btn-success\">회원가입</button>\r\n");
      out.write("				</td>\r\n");
      out.write("			</tr>\r\n");
      out.write("		<!--     아이디 : <input type=\"text\" name=\"user_id\" size=\"10\" class=\"form-control form-control-sm\" id=\"idForm\">\r\n");
      out.write("		    비밀번호 : <input type=\"password\" name=\"user_passwd\" size=\"10\">\r\n");
      out.write("		    <input type=\"hidden\" name=\"actionType\" value=\"LOGIN\">\r\n");
      out.write("		    <input type=\"submit\" value=\"로그인\"> -->\r\n");
      out.write("		    	</table>\r\n");
      out.write("		 </form>\r\n");
      out.write("		 \r\n");
      out.write("		");
      out.write("\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");

	}

      out.write("\r\n");
      out.write("</nav>\r\n");
      out.write("\r\n");
      out.write("<!-- <div style=\"display: flex; justify-content: center;\"> -->\r\n");
      out.write("	<div style=\"text-align:center\">\r\n");
      out.write("	<!-- 	<ul class=\"list-group\"> -->\r\n");
      out.write("	<a href=\"./getBoardgameList.be?currentPage=0&category=strategy\" style = \"margin-left:50px\">전략 게임</a>\r\n");
      out.write(" 	<a href=\"./getBoardgameList.be?currentPage=0&category=party\" style = \"margin-left:50px\" >파티 게임</a>\r\n");
      out.write(" 	<a href=\"./getBoardgameList.be?currentPage=0&category=new\"style = \"margin-left:50px\">신상 게임</a>\r\n");
      out.write(" 	<a href=\"./getBoardgameList.be?currentPage=0&category=school\" style = \"margin-left:50px\">학교용 교구</a>\r\n");
      out.write(" 	<a href=\"./getBoardgameList.be?currentPage=0&category=first\"style = \"margin-left:50px\">선주문</a>\r\n");
      out.write(" 	<a href=\"./getBoardgameList.be?currentPage=0&category=best\" style = \"margin-right:0px\" >베스트 100</a>\r\n");
      out.write(" 	<!-- 	</ul> -->\r\n");
      out.write(" 	</div>\r\n");
      out.write("<!-- </div> -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<hr> \r\n");
      out.write("	<!-- <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js\"></script>\r\n");
      out.write("	<script src=\"JS/bootstrap.js\"></script> -->\r\n");
      out.write("	\r\n");
      out.write("	<script type =\"text/javascript\" src=\"");
      out.print(jsUserDir);
      out.write("/infochk.js\"></script>\r\n");
      out.write("		<script type =\"text/javascript\" src=\"");
      out.print(jsBoardgameDir);
      out.write("/b_infochk.js\"></script>\r\n");
      out.write("	<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js\"></script>\r\n");
      out.write("	<link rel=\"stylesheet\" \r\n");
      out.write("	href=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css\" \r\n");
      out.write("	integrity=\"sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N\" \r\n");
      out.write("	crossorigin=\"anonymous\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css\">\r\n");
      out.write("	\r\n");
      out.write("	<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css\"\r\n");
      out.write("	integrity=\"sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N\"\r\n");
      out.write("	crossorigin=\"anonymous\">\r\n");
      out.write("	\r\n");
      out.write("<!-- <script\r\n");
      out.write("	src=\"https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js\"\r\n");
      out.write("	integrity=\"sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj\"\r\n");
      out.write("	crossorigin=\"anonymous\"></script>\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js\"\r\n");
      out.write("	integrity=\"sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct\"\r\n");
      out.write("	crossorigin=\"anonymous\"></script>\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js\"\r\n");
      out.write("	integrity=\"sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj\"\r\n");
      out.write("	crossorigin=\"anonymous\"></script>\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js\"\r\n");
      out.write("	integrity=\"sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN\"\r\n");
      out.write("	crossorigin=\"anonymous\"></script>\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.min.js\"\r\n");
      out.write("	integrity=\"sha384-+sLIOodYLS7CIrQpBjl+C7nPvqq+FbNUBDunl/OZv93DB7Ln/533i8e/mZXLi/P+\"\r\n");
      out.write("	crossorigin=\"anonymous\"></script>\r\n");
      out.write("	 -->\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<!-- <form id=\"form\" method=\"post\" action=\"./insertBoardgame.be\" enctype=\"multipart/form-data\">\r\n");
      out.write("\r\n");
      out.write("	<br>상품 코드 : <input type=\"text\" id=\"b_code\" name=\"b_code\" size = 30  required>\r\n");
      out.write("	<br><span id=\"codechk\"></span>\r\n");
      out.write("	\r\n");
      out.write("	<br>상품 종류: <input type=\"text\" name=\"\" size = 30 required id=\"b_category\">\r\n");
      out.write("	<br>상품 종류: <select name = \"b_category\" id = \"b_category\">\r\n");
      out.write("				<option value = \"strategy\" selected>전략</option>\r\n");
      out.write("				<option value = \"party\">파티</option>\r\n");
      out.write("				<option value = \"new\">신상</option>\r\n");
      out.write("				<option value = \"school\">교구</option>\r\n");
      out.write("				<option value = \"first\">선 주문</option>\r\n");
      out.write("				<option value = \"best\">베스트</option>\r\n");
      out.write("			</select>\r\n");
      out.write("	\r\n");
      out.write("	<br>상품 이름 : <input type=\"text\" name=\"b_name\"  size = 30 required id =\"b_name\" >\r\n");
      out.write("	<br><span id=\"name_chk\"></span>\r\n");
      out.write("	\r\n");
      out.write("	<br>상품 가격 : <input type=\"number\"name=\"b_price\" size = 30 required placeholder=\"원 단위\">\r\n");
      out.write("	<br>\r\n");
      out.write("	\r\n");
      out.write("	<br>상품 적정연령: <input type=\"number\" name=\"b_age\" size = 30  maxlength=\"14\" required >\r\n");
      out.write("	 <select name = \"b_agestate\" id = \"b_agestate\">\r\n");
      out.write("				<option value = \"이상\" selected>세 이상 사용</option>\r\n");
      out.write("				<option value = \"이하\">세 이하 사용</option>\r\n");
      out.write("				<option value = \"미만\">세 미만 사용금지</option>\r\n");
      out.write("			\r\n");
      out.write("			</select>\r\n");
      out.write("	<br><span id=age_chk></span>\r\n");
      out.write("	\r\n");
      out.write("	<br>상품 플레이어 : <input type=\"number\"  name=\"b_player1\" size = 30 id =\"b_player1\">~<input type=\"number\"  name=\"b_player2\" size = 30 id =\"b_player2\">\r\n");
      out.write("	\r\n");
      out.write("	<br>상품 플레이시간 : <input type=\"number\"  name=\"b_time1\" size = 30 id =\"b_time1\" >~<input type=\"number\"  name=\"b_time2\" size = 30 id =\"b_time2\">\r\n");
      out.write("	<br><span id=time_chk></span>\r\n");
      out.write("	\r\n");
      out.write("	<br>상품 설명 : <textarea rows=\"10\" cols=\"100\" name = \"b_content\" maxlength = 500 id = \"b_content\" placeholder=\"500자 이상 사용금지\"></textarea>\r\n");
      out.write("	textarea로 글자수 제한 넣기\r\n");
      out.write("	\r\n");
      out.write("	<br>상품 배송비 : <input type=\"number\" name=\"b_charge\" size = 30 value=\"0\">\r\n");
      out.write("	<br><span id=charge_chk></span>\r\n");
      out.write("	\r\n");
      out.write("	<br>상품 기본사진 : <input type =\"file\" name =\"b_image\">\r\n");
      out.write("	\r\n");
      out.write("	<br><input type=\"submit\"  value=\"상품등록\">\r\n");
      out.write("</form> -->\r\n");
      out.write("\r\n");
      out.write("<div class=\"container center\" >\r\n");
      out.write("	\r\n");
      out.write("		<div class=\"col-lg-7 center\" >\r\n");
      out.write("			<div class=\"jumbotron\" style=\"padding-top: 20px;\">\r\n");
      out.write("				<h3 style=\"text-align: center;\" class=\"mb-4\">회원가입</h3>\r\n");
      out.write("				\r\n");
      out.write("				<!-- form -->\r\n");
      out.write("				\r\n");
      out.write("			<form id=\"form\" method=\"post\" action=\"./insertBoardgame.be\" enctype=\"multipart/form-data\">\r\n");
      out.write("					<!-- 경로 수정 -->\r\n");
      out.write("					<div class=\"form-group\">\r\n");
      out.write("						<div>\r\n");
      out.write("							<span>상품 코드</span>\r\n");
      out.write("							<input class=\"form-control mb-2\"  type=\"text\" id=\"b_code\" name=\"b_code\" size = 30  required placeholder=\"상품 코드\">\r\n");
      out.write("							<span id=\"codechk\"></span>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("					<div class=\"form-group\">\r\n");
      out.write("						<span>상품 종류</span>\r\n");
      out.write("						<select class=\"form-control mb-2\"  name = \"b_category\" id = \"b_category\">\r\n");
      out.write("							<option value = \"strategy\" selected>전략</option>\r\n");
      out.write("							<option value = \"party\">파티</option>\r\n");
      out.write("							<option value = \"new\">신상</option>\r\n");
      out.write("							<option value = \"school\">교구</option>\r\n");
      out.write("							<option value = \"first\">선 주문</option>\r\n");
      out.write("							<option value = \"best\">베스트</option>\r\n");
      out.write("						</select>\r\n");
      out.write("					\r\n");
      out.write("					</div>\r\n");
      out.write("		\r\n");
      out.write("					<!-- 비밀번호 -->\r\n");
      out.write("					<div class=\"form-group\">\r\n");
      out.write("				\r\n");
      out.write("						<span>상품 이름</span>\r\n");
      out.write("						<input class=\"form-control mb-2\"  type=\"text\" name=\"b_name\"  size = 30 required id =\"b_name\" placeholder=\"상품 이름\" >\r\n");
      out.write("						<span id=\"name_chk\"></span>\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("					<div class=\"form-group has-danger\">\r\n");
      out.write("						<span>상품 가격</span>\r\n");
      out.write("						<input class=\"form-control mb-2\" type=\"number\"name=\"b_price\" size = 30 required placeholder=\"원 단위\">\r\n");
      out.write("					\r\n");
      out.write("					</div>\r\n");
      out.write("						\r\n");
      out.write("						\r\n");
      out.write("					<div class=\"form-group\">\r\n");
      out.write("			\r\n");
      out.write("							<span>상품 적정연령</span><br>\r\n");
      out.write("							 <input class=\"col-md-6 mb-2\"type=\"number\" name=\"b_age\" size = 30  maxlength=\"14\" required >\r\n");
      out.write("							 <select class=\"col-md-5 mb-2\" name = \"b_agestate\" id = \"b_agestate\">\r\n");
      out.write("										<option value = \"이상\" selected>세 이상 사용</option>\r\n");
      out.write("										<option value = \"이하\">세 이하 사용</option>\r\n");
      out.write("										<option value = \"미만\">세 미만 사용금지</option>\r\n");
      out.write("									\r\n");
      out.write("									</select>\r\n");
      out.write("							<span id=age_chk></span>\r\n");
      out.write("				\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("					<div class=\"form-group\">\r\n");
      out.write("					\r\n");
      out.write("						<span>상품 플레이어</span><br>\r\n");
      out.write("						<input class=\"col-md-5 mb-2\" type=\"number\"  name=\"b_player1\" size = 30 id =\"b_player1\">~<input  class=\"col-md-5 mb-2\" type=\"number\"  name=\"b_player2\" size = 30 id =\"b_player2\">\r\n");
      out.write("				\r\n");
      out.write("					</div>\r\n");
      out.write("					\r\n");
      out.write("					<div class=\"form-group\">\r\n");
      out.write("					\r\n");
      out.write("						<span>상품 플레이시간</span><br>\r\n");
      out.write("						<input class=\"col-md-5 mb-2\" type=\"number\"  name=\"b_time1\" size = 30 id =\"b_time1\">~<input  class=\"col-md-5 mb-2\" type=\"number\"  name=\"b_time2\" size = 30 id =\"b_time2\">\r\n");
      out.write("				\r\n");
      out.write("					</div>\r\n");
      out.write("					\r\n");
      out.write("					<div class=\"form-group\">\r\n");
      out.write("	\r\n");
      out.write("						<span>상품 설명 </span><br>\r\n");
      out.write("						 <textarea class=\"form-control mb-2\"  rows=\"10\" cols=\"100\" name = \"b_content\" maxlength = 500 id = \"b_content\" placeholder=\"500자 이상 사용금지\"></textarea>\r\n");
      out.write("						\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"form-group\">\r\n");
      out.write("						<span>상품 배송비</span>\r\n");
      out.write("						 <input class=\"form-control mb-2\" type=\"number\" name=\"b_charge\" size = 30 value=\"0\">\r\n");
      out.write("						<span id=charge_chk></span>\r\n");
      out.write("					\r\n");
      out.write("					</div>\r\n");
      out.write("						<span>상품 기본사진</span>\r\n");
      out.write("						<input type =\"file\" name =\"b_image\">\r\n");
      out.write("					<input class=\"btn btn-success float-right\" style=\"margin-left: 10px;\" type=\"submit\"  value=\"상품 등록\">\r\n");
      out.write("						\r\n");
      out.write("				</form>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	<!-- 	<div class=\"col-lg-4\"></div> -->\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<hr>\r\n");
      out.write("<table>\r\n");
      out.write("	<div>\r\n");
      out.write("		<tr>사이트 대표자명 : 유원규 </tr>\r\n");
      out.write("		<tr>전화번호 : 053-123-4567 </tr>\r\n");
      out.write("		<tr>주소 : 대구 북구 복현로 35</tr>\r\n");
      out.write("		<tr>사업자 등록번호 : 1234567891 </tr>\r\n");
      out.write("		<tr>메일 : hongildong@boardmoa.com</tr>\r\n");
      out.write("	</div>\r\n");
      out.write("</table>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
